<script setup lang="ts">
import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { computed } from "vue";
import AutoStartGate from "./components/AutoStartGate.vue";
import AutoToggle from "./components/AutoToggle.vue";
import ProgressBar from "./components/ProgressBar.vue";
import Stage from "./components/Stage.vue";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ~ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

const stepper = useStepper(CHAPTERS);

const ch = computed(() => CHAPTERS[stepper.chapter.value] ?? CHAPTERS[0]);
const stepText = computed(() => ch.value?.narrations?.[stepper.step.value] ?? "");

const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

// Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
// (1-indexed file names match what `extract-narrations.ts` outputs.)
// Empty narration → no audio src, Auto mode falls back to estimate.
const audioSrc = computed(() => {
  if (mode.value === "manual" || stepText.value === "" || !ch.value) return null;
  return `${import.meta.env.BASE_URL}audio/${ch.value.id}/${stepper.step.value + 1}.mp3`;
});

useAudioPlayer({
  src: audioSrc,
  mode,
  trailMs: 200,
  estimateFallbackMs: () => estimateMs(stepText.value),
  onAutoAdvance: stepper.next,
  autoStarted,
});
</script>

<template>
  <Stage :on-advance="stepper.next">
    <div :key="ch.id" class="scene">
      <component :is="ch.Component" :step="stepper.step.value" />
    </div>
  </Stage>
  <ProgressBar
    :chapters="CHAPTERS"
    :cursor="stepper.cursor"
    :on-jump-chapter="stepper.jumpToChapter"
  />
  <AutoToggle :mode="mode" :on-cycle="cycleMode" />
  <AutoStartGate
    :visible="mode === 'auto' && !autoStarted"
    :on-start="() => setAutoStarted(true)"
  />
</template>
